Update Adafruit_SPIDevice.cpp
adafruit/Adafruit_BusIO pull request #39
Opened 2020-11-28 20:50 UTC by howard-wa9axq

The SPI.cpp that the STM32 project uses does not have a transfer method with both a buffer and a length.  Changes to this file uses a transfer method that just needs a single 8 bit character.

Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

2020-11-28 21:48 UTC, ladyada commented
for STM32, add an #ifdef like we have for the SPARK in preceding lines. many chips have DMA or optimized transfer, even if STM32 does not

2020-11-28 21:48 UTC, ladyada requested changes
put in an ifdef, dont change behavior for every other chip

2020-11-28 23:56 UTC, ladyada commented
please use
``` 
#if defined()
#elsif defined()
#else
#endif
```
for multiple options as shown here
https://github.com/adafruit/Adafruit_BusIO/blob/master/Adafruit_SPIDevice.h#L7

2020-11-29 02:22 UTC, ladyada approved these changes

2020-11-29 02:23 UTC, merged

2020-11-29 02:23 UTC, ladyada commented
thanx!

2020-11-29 10:59 UTC, AnHardt commented
`STM32` is a to un-sharp discriminator. This has to be done by core.

https://github.com/stm32duino/Arduino_Core_STM32/blob/master/libraries/SPI/src/SPI.h#L194-L197
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/libraries/SPI/src/SPI.h#L277-L301