streamlined transaction management
adafruit/Adafruit_BusIO pull request #90
Opened 2022-04-18 15:28 UTC by eringerli

These changes streamline the transaction management. It reuses already
existing methods and lowers the amount of duplicated code.

2022-04-18 16:34 UTC, eringerli commented on Adafruit_SPIDevice.cpp
> +    if (len) {
there is a huge performance gain here: instead of reading each byte individually, do it in one go

2022-05-01 16:16 UTC, eringerli commented
@ladyada Is there something which still blocks this PR? This lowers the amount of dupicated code, removes the need for special-casing the ESP32 and improves the performance tremendiously on all platforms which support multibyte transfers. It is also fully backwards compatible and doesn't change the memory footprint.

2022-05-02 02:13 UTC, ladyada commented
we want to avoid merging any PRs we get that could break our libraries so we like to be very careful. everyone thinks their PRs are perfect, drop-in compatible, and don't break anything - however, that's true only half the time ;) please see other posting where we request splitting the PR into two conceptual changes

2022-05-02 04:45 UTC, eringerli commented
Can you tell me, how I can split this one further?

2022-05-02 12:17 UTC, eringerli commented
I hope splitting the commit up into method-wise commits clears the changes up

2022-05-02 16:06 UTC, ladyada requested changes

2022-05-02 16:06 UTC, ladyada commented on Adafruit_SPIDevice.cpp
> +void Adafruit_SPIDevice::setChipSelect(int value) {
fyi can make this inline if you like, to speed it up

2022-05-02 16:06 UTC, ladyada commented on Adafruit_SPIDevice.cpp
> +  if (prefix_buffer == nullptr) {
remove this part, we're only handling CS/begintransaction in this PR

2022-05-02 16:06 UTC, ladyada commented on Adafruit_SPIDevice.cpp
> +      transfer(const_cast<uint8_t *>(prefix_buffer), prefix_len);
remove this part, we're only handling CS/begintransaction in this PR

2022-05-02 16:06 UTC, ladyada commented on Adafruit_SPIDevice.cpp
> -#if defined(ARDUINO_ARCH_ESP32)
undo this part, we're only handling CS/begintransaction in this PR

2022-05-02 16:06 UTC, ladyada commented on Adafruit_SPIDevice.cpp
> +  write_and_read(buffer, len);
undo this part, we're only handling CS/begintransaction in this PR

2022-05-02 16:06 UTC, ladyada commented on Adafruit_SPIDevice.cpp
> +    transfer(const_cast<uint8_t *>(write_buffer), write_len);
undo this part, we're only handling CS/begintransaction in this PR

2022-05-02 16:06 UTC, ladyada commented on Adafruit_SPIDevice.cpp
> -#if defined(ARDUINO_ARCH_ESP32)
undo this part, we're only handling CS/begintransaction in this PR

2022-05-02 16:06 UTC, ladyada commented on Adafruit_SPIDevice.cpp
> +    transfer(read_buffer, read_len);
undo this part, we're only handling CS/begintransaction in this PR

2022-05-02 16:07 UTC, ladyada commented
i dont know whats going on with your PR setup but the changes aren't coming thru. i recommend starting over with a new PR so you can see the changes clearly

2022-05-02 17:58 UTC, closed without merging